feature-toggles:
  toggles:
    foo:
      enabled: true
    secret-foo:
      enabled: true
      roles: ["ROLE_USER"]
    new-dashboard:
      enabled: true
      roles: ["ADMIN", "USER"]
      experimentPercentage: 50
    

logging:
  level:
    # org.springframework: DEBUG
    net.caimito.features: DEBUG